[package]
name = "nix-interactive"
version = "0.1.0"
edition = "2021"
description = "Interactive historical diff viewer for Nix generations"
license = "MIT"

[[bin]]
name = "nixi"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "4", features = ["derive", "env"] }
ratatui = "0.30.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
